baseURL = "https://www.save-food-culture.ml/"

languageCode = "ja-jp"
DefaultContentLanguage = "ja"
title = "Save Food Culture - 飲食店支援情報まとめ"
theme = "hugo-theme-techdoc"
googleAnalytics = "UA-165582058-1"

hasCJKLanguage = "true"
enableGitInfo = "true"

[params]
    github_repository = "https://github.com/tunepolo/hack-the-crisis-for-food-culture"
    github_doc_repository = "https://github.com/tunepolo/hack-the-crisis-for-food-culture"

    menu_style = "open-menu"

		# OGP setting
		title = "Save Food Culture"
		images = ["images/home.jpg"]

    # Theme color
    # See color value reference https://developer.mozilla.org/en-US/docs/Web/CSS/color
    custom_font_color = ""
    custom_background_color = "orange"

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "About"
				url = "/about"
				weight = 2

    [[menu.main]]
        name = "経産省 新型コロナウイルス関連"
        url = "https://www.meti.go.jp/covid-19/"
        weight = 3

# Markup configure section
# See https://gohugo.io/getting-started/configuration-markup/
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark.renderer]
        unsafe= true
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 4
        ordered = false
